# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='翻堆序号')),
                ('plannedAt', models.DateTimeField(verbose_name='计划翻堆时刻')),
                ('doneAt', models.DateTimeField(blank=True, null=True, verbose_name='实做时刻')),
                ('operator', models.CharField(max_length=80, verbose_name='当班人')),
                ('settled', models.BooleanField(default=False, verbose_name='是否销账')),
                ('trough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_ledgers', to='gardens.trough', verbose_name='所属槽位')),
            ],
            options={
                'verbose_name': '翻堆节拍账',
                'verbose_name_plural': '翻堆节拍账',
                'ordering': ['trough', 'sequence'],
                'indexes': [models.Index(fields=['trough', 'settled'], name='turn_open_idx')],
                'constraints': [models.UniqueConstraint(fields=('trough', 'sequence'), name='uniq_turn_sequence_per_trough')],
            },
        ),
    ]
